# Generated by Django 5.2.17 on 2026-09-24 23:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('source_file', models.CharField(editable=False, max_length=180, unique=True)),
            ],
            options={
                'verbose_name': 'verkkosivu',
                'verbose_name_plural': 'Verkkosivut',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='Toimipaikka')),
                ('street', models.CharField(max_length=200, verbose_name='Katuosoite')),
                ('postal', models.CharField(max_length=120, verbose_name='Postinumero ja kaupunki')),
                ('phone', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Puhelin (näytettävä)')),
                ('tel', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Puhelin (kansainvälinen)')),
                ('hours', models.CharField(max_length=200, verbose_name='Aukioloajat')),
                ('hours_en', models.CharField(blank=True, max_length=200, verbose_name='Aukioloajat englanniksi')),
                ('original', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'toimipaikka',
                'verbose_name_plural': 'Toimipaikat',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='site', editable=False, max_length=12, unique=True)),
                ('name', models.CharField(default='Kontturi & Co', max_length=120, verbose_name='Toimiston nimi')),
                ('email', models.EmailField(max_length=254, verbose_name='Yleinen sähköposti')),
                ('on_call_phone', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Päivystysnumero (näytettävä)')),
                ('on_call_tel', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Päivystysnumero (kansainvälinen)')),
                ('original', models.JSONField(default=dict, editable=False)),
            ],
            options={
                'verbose_name': 'sivuston yhteystiedot',
                'verbose_name_plural': 'Sivuston yhteystiedot',
            },
        ),
        migrations.CreateModel(
            name='ImportedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250, unique=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.PositiveIntegerField(editable=False)),
                ('label', models.CharField(editable=False, max_length=200, verbose_name='Alkuperäinen kuva')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='Vaihtoehtoinen teksti')),
                ('image', models.ForeignKey(blank=True, help_text='Tyhjä valinta säilyttää alkuperäisen kuvan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_replacements', to='wagtailimages.image', verbose_name='Korvaava kuva')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.legacypage')),
            ],
            options={
                'verbose_name': 'kuva',
                'verbose_name_plural': 'Kuvat',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.PositiveIntegerField(editable=False)),
                ('label', models.CharField(editable=False, max_length=200, verbose_name='Kohta')),
                ('value', models.TextField(max_length=20000, verbose_name='Teksti')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='content.legacypage')),
            ],
            options={
                'verbose_name': 'teksti',
                'verbose_name_plural': 'Tekstit',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=160, verbose_name='Nimi')),
                ('role', models.CharField(max_length=250, verbose_name='Tehtävänimike')),
                ('phone', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Puhelin (näytettävä)')),
                ('tel', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^\\+?[0-9 ()-]{5,30}$', 'Kirjoita kelvollinen puhelinnumero.')], verbose_name='Puhelin (kansainvälinen)')),
                ('email', models.EmailField(max_length=254, verbose_name='Sähköposti')),
                ('profile_slug', models.SlugField(editable=False)),
                ('topic', models.CharField(blank=True, choices=[('yritys', 'Yritysjuridiikka'), ('kiinteistot', 'Kiinteistöt'), ('perhe', 'Perhe ja perintö'), ('muu', 'Muu')], max_length=30, verbose_name='Yhteydenoton oletusaihe')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Järjestys')),
                ('original', models.JSONField(default=dict, editable=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_portraits', to='wagtailimages.image', verbose_name='Uusi henkilökuva')),
            ],
            options={
                'verbose_name': 'asiantuntija',
                'verbose_name_plural': 'Asiantuntijat',
                'ordering': ['sort_order', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(max_length=1000, verbose_name='Johdanto')),
                ('category', models.CharField(default='Ajankohtaista', max_length=100, verbose_name='Aihe')),
                ('body', wagtail.fields.RichTextField(verbose_name='Artikkelin sisältö')),
                ('cover_alt', models.CharField(blank=True, max_length=300, verbose_name='Kuvan vaihtoehtoinen teksti')),
                ('publication_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Julkaisupäivä')),
                ('legacy_file', models.CharField(blank=True, editable=False, max_length=180)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_covers', to='wagtailimages.image', verbose_name='Artikkelikuva')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.person', verbose_name='Kirjoittaja')),
            ],
            options={
                'verbose_name': 'artikkeli',
                'verbose_name_plural': 'Artikkelit',
            },
            bases=('wagtailcore.page',),
        ),
    ]
