# Generated by Django 5.2.17 on 2026-09-24 23:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='publication_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True, verbose_name='Julkaisupäivä'),
        ),
    ]
